version: '2'

services:
  app:
    build: .
    container_name: app
    volumes: 
      - ".:/usr/src/app"
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
    ports:
     - "${PORT}:3000"
    command: npm run serve
