version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: app
    environment:
      PORT: 3000
    volumes: 
      - ".:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
     - "3000:3000"
    command: npm run serve
